name = "AoC"
uuid = "e588f982-541e-4562-9118-613a6f6b7ce6"
authors = ["Petr Pošík"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
